# Generated by Django 3.1.3 on 2020-12-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('morningapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=25)),
                ('headimg', models.CharField(default='http://127.0.0.1:9000/upload/headDefaultImg.jpeg/', max_length=200)),
                ('sex', models.CharField(blank=True, max_length=4)),
                ('birth', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=4)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=10)),
                ('sign', models.CharField(blank=True, max_length=200)),
                ('belong', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='morningapp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('weixin', models.CharField(blank=True, max_length=20)),
                ('qq', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('github', models.CharField(blank=True, max_length=20)),
                ('weibo', models.CharField(blank=True, max_length=20)),
                ('belong', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='morningapp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('cover', models.CharField(blank=True, default='http://127.0.0.1:9000/upload/pic.png', max_length=300, null=True)),
                ('describe', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('createtime', models.DateField(blank=True, null=True)),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_user', to='morningapp.userinfo')),
            ],
        ),
    ]
