# Generated by Django 3.1.3 on 2020-12-06 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('morningapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('cover', models.CharField(blank=True, default='https://api.tian999.top/upload/pic.png', max_length=300, null=True)),
                ('describe', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('createtime', models.DateField(blank=True, null=True)),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morningapp.article')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morningapp.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(through='morningapp.Tag_Article', to='morningapp.Article'),
        ),
        migrations.AddField(
            model_name='tag',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag_children', to='morningapp.tag'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=25)),
                ('headimg', models.CharField(default='https://api.tian999.top/upload/headDefaultImg.jpeg', max_length=200)),
                ('sex', models.CharField(blank=True, max_length=4)),
                ('birth', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=4)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=10)),
                ('sign', models.CharField(blank=True, max_length=200)),
                ('belong', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('moodname', models.CharField(max_length=200)),
                ('createtime', models.DateField(blank=True, null=True)),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('weixin', models.CharField(blank=True, max_length=20)),
                ('qq', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('github', models.CharField(blank=True, max_length=20)),
                ('weibo', models.CharField(blank=True, max_length=20)),
                ('belong', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
