# Generated by Django 3.1.3 on 2020-12-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0002_auto_20201206_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
