# Generated by Django 3.1.3 on 2020-12-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0002_article_contact_profile_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_id',
            new_name='userID',
        ),
    ]
