# Generated by Django 3.1.3 on 2020-12-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0003_auto_20201204_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagname', models.CharField(max_length=20)),
                ('belong', models.ManyToManyField(to='morningapp.Article')),
            ],
        ),
    ]
