# Generated by Django 3.1.3 on 2020-12-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0003_auto_20201202_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='belong',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morningapp.userinfo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='belong',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morningapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
