# Generated by Django 3.1.3 on 2020-12-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0004_auto_20201202_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='belong',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_user', to='morningapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='belong',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='morningapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='github',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='qq',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='weibo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='weixin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='belong',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='morningapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headimg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sign',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
