# Generated by Django 3.1.3 on 2020-12-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0004_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='belong',
            field=models.ManyToManyField(null=True, to='morningapp.Article'),
        ),
    ]
