# Generated by Django 3.1.3 on 2020-12-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0005_auto_20201204_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='belong',
        ),
        migrations.CreateModel(
            name='Tag_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morningapp.article')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morningapp.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(through='morningapp.Tag_Article', to='morningapp.Article'),
        ),
    ]
