# Generated by Django 3.1.3 on 2020-12-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0006_auto_20201204_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.CharField(blank=True, default='https://api.tian999.top/upload/pic.png', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headimg',
            field=models.CharField(default='https://api.tian999.top/upload/headDefaultImg.jpeg', max_length=200),
        ),
    ]
