# Generated by Django 3.1.3 on 2020-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0006_profile_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
