# Generated by Django 3.1.3 on 2020-12-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0007_article_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='headimg',
            field=models.CharField(default='http://127.0.0.1:9000/upload/headDefaultImg.jpeg/', max_length=200),
        ),
    ]
