# Generated by Django 3.1.3 on 2020-12-04 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0007_auto_20201204_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='分类', to='morningapp.tag_article'),
        ),
    ]
