# Generated by Django 3.1.3 on 2020-12-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0008_tag_article_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_article',
            name='parent',
        ),
        migrations.AddField(
            model_name='tag',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag_children', to='morningapp.tag'),
        ),
    ]
