# Generated by Django 3.1.3 on 2020-12-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0009_auto_20201203_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id',
            new_name='article_id',
        ),
    ]
