# Generated by Django 3.1.3 on 2020-12-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0009_auto_20201204_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('moodname', models.CharField(max_length=200)),
                ('createtime', models.DateField(blank=True, null=True)),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood_user', to='morningapp.userinfo')),
            ],
        ),
    ]
