# Generated by Django 3.1.3 on 2020-12-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morningapp', '0010_auto_20201203_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='birth',
            new_name='createtime',
        ),
    ]
